[package]
name = "node"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.128"
rmp-serde = "1.0"
murmur3 = "0.5.1"
chrono = "0.4.38"
rand = "0.8.5"